const KEY="mdacExpressV4";
const officialUrl="https://imigresen-online.imi.gov.my/mdac/main?registerMain";
const defaults={profiles:[{id:"p1",label:"Traveller 1",name:"",passportNo:"",dob:"01/01/1970",nationality:"USA",placeOfBirth:"USA",sex:"M",passportExpiry:"01/01/2030",email:"",phoneCountry:"SGP",mobile:""}],activeProfileId:"p1",settings:{defaultTrip:"weekend",rememberHistory:true},history:{transport:[],hotel:[]},trip:{transportNo:"",modeOfTravel:"LAND",lastPort:"SGP",accommodationStay:"OTHERS",address1:"106 JALAN WONG AH FOOK",address2:"JOHOR BAHRU CITY SQUARE",state:"JOHOR",city:"JOHOR BAHRU",postcode:"80000",departureOffset:1}};
let state=load();let view="home";let selectedTrip="weekend";
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")} }catch(e){return defaults}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function $(id){return document.getElementById(id)}
function activeProfile(){return state.profiles.find(p=>p.id===state.activeProfileId)||state.profiles[0]}
function fmtDate(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return String(d.getDate()).padStart(2,"0")+"/"+String(d.getMonth()+1).padStart(2,"0")+"/"+d.getFullYear()}
function payloadFor(kind=selectedTrip){const p=activeProfile();const isDay=kind==="day";const isFlight=kind==="flight";const isBus=kind==="bus";const isTrain=kind==="train";const isFerry=kind==="ferry";let mode=isFlight?"AIR":isFerry?"SEA":"LAND";return {profile:p,trip:{arrivalDate:fmtDate(0),departureDate:fmtDate(isDay?0:state.trip.departureOffset||1),modeOfTravel:mode,lastPort:state.trip.lastPort||"SGP",transportNo:state.trip.transportNo||"",accommodationStay:state.trip.accommodationStay||"OTHERS",address1:state.trip.address1,address2:state.trip.address2,state:state.trip.state,city:state.trip.city,postcode:state.trip.postcode}}}
function copyPayload(kind){const data=payloadFor(kind);navigator.clipboard.writeText("MDAC_EXPRESS:"+JSON.stringify(data)).then(()=>alert("Payload copied. Now open MDAC, then Share → Fill MDAC."))}
function render(){document.querySelector("#app").innerHTML=`<main class="shell">${header()}${views[view]()}${tabs()}</main>`;wire()}
function header(){const p=activeProfile();return `<div class="top"><div class="brand"><div class="logo">🇲🇾</div><div><h1>MDAC Express</h1><p class="sub">${p.label||"Traveller"} · local only</p></div></div><button class="pill" data-view="profiles">Switch</button></div>`}
const tripTiles=[['weekend','🚗','Weekend Johor','Depart tomorrow'],['day','⚡','Day Trip','Return today'],['flight','✈️','Flight','Air arrival'],['bus','🚌','Bus','Land arrival'],['train','🚆','Train','Rail arrival'],['ferry','⛴️','Ferry','Sea arrival']];
const views={home(){return `<section class="hero"><h2>Fill MDAC faster</h2><p>Prepare your traveller and trip data, then use the Safari Shortcut on the official MDAC page. You still review and submit manually.</p></section><section class="grid">${tripTiles.map(t=>`<button class="tile" data-trip="${t[0]}"><span class="ico">${t[1]}</span><span class="title">${t[2]}</span><span class="hint">${t[3]}</span></button>`).join('')}</section><div class="card"><h2>Quick action</h2><button class="primary" data-copy="weekend">Prepare Weekend Johor</button><button class="secondary" data-open>Open official MDAC</button></div>`},
trip(){const t=payloadFor(selectedTrip).trip;return `<button class="back" data-view="home">‹ Back</button><div class="card"><h2>${tripTiles.find(x=>x[0]===selectedTrip)?.[2]||'Trip'}</h2><div class="row"><div class="field"><label>Transport no.</label><input id="transportNo" value="${state.trip.transportNo||''}" placeholder="Car plate / flight / bus" /></div></div><div class="row two"><div class="field"><label>Arrival</label><input disabled value="${t.arrivalDate}" /></div><div class="field"><label>Departure</label><input disabled value="${t.departureDate}" /></div></div><div class="notice">Mode: <b>${t.modeOfTravel}</b> · Last port: <b>${t.lastPort}</b> · Address: <b>${t.city}, ${t.state}</b></div><button class="primary" data-copy="${selectedTrip}">Prepare MDAC</button><button class="secondary" data-open>Open official MDAC</button></div>`},
profiles(){const p=activeProfile();return `<div class="card"><h2>Profiles</h2><div class="list">${state.profiles.map(x=>`<button class="item" data-profile="${x.id}"><div><b>${x.label}</b><span>${x.passportNo?x.passportNo:'No passport saved'}</span></div><span>${x.id===state.activeProfileId?'✓':''}</span></button>`).join('')}</div><button class="secondary" data-add-profile>Add profile</button></div><div class="card"><h2>Edit active profile</h2>${profileFields(p)}<button class="primary" data-save-profile>Save profile</button></div>`},
settings(){return `<div class="card"><h2>Trip defaults</h2><div class="row"><div class="field"><label>Default transport no.</label><input id="d_transportNo" value="${state.trip.transportNo||''}" /></div><div class="field"><label>Last port before Malaysia</label><input id="d_lastPort" value="${state.trip.lastPort||'SGP'}" /></div><div class="field"><label>Accommodation type</label><input id="d_accommodationStay" value="${state.trip.accommodationStay||'OTHERS'}" /></div><div class="field"><label>Address line 1</label><input id="d_address1" value="${state.trip.address1||''}" /></div><div class="field"><label>Address line 2</label><input id="d_address2" value="${state.trip.address2||''}" /></div></div><div class="row two"><div class="field"><label>State</label><input id="d_state" value="${state.trip.state||'JOHOR'}" /></div><div class="field"><label>City</label><input id="d_city" value="${state.trip.city||'JOHOR BAHRU'}" /></div></div><div class="row two"><div class="field"><label>Postcode</label><input id="d_postcode" value="${state.trip.postcode||'80000'}" /></div><div class="field"><label>Departure offset</label><select id="d_departureOffset"><option value="0">Same day</option><option value="1">Tomorrow</option><option value="2">+2 days</option></select></div></div><button class="primary" data-save-settings>Save defaults</button></div><div class="card"><h2>Data</h2><button class="secondary" data-export>Export backup</button><button class="secondary" data-import>Import backup</button><button class="danger" data-reset>Reset all data</button></div>`},
help(){return `<div class="card"><h2>How to use</h2><div class="notice">1. Save your profile.<br>2. Choose a trip preset.<br>3. Tap Prepare MDAC.<br>4. Open the official MDAC page.<br>5. On that page, tap Share → Fill MDAC.<br>6. Review, solve CAPTCHA, submit.</div><button class="secondary" data-open>Open official MDAC</button></div><div class="card"><h2>Shortcut</h2><p class="sub">Use the Safari Shortcut script from <b>autofill-shortcut.js</b>. It reads the copied payload and fills the official form.</p></div>`}};
function profileFields(p){return `<div class="row"><div class="field"><label>Profile label</label><input id="label" value="${p.label||''}"></div><div class="field"><label>Full name as in passport</label><input id="name" value="${p.name||''}"></div><div class="field"><label>Passport no.</label><input id="passportNo" value="${p.passportNo||''}"></div></div><div class="row two"><div class="field"><label>DOB DD/MM/YYYY</label><input id="dob" value="${p.dob||''}"></div><div class="field"><label>Passport expiry</label><input id="passportExpiry" value="${p.passportExpiry||''}"></div></div><div class="row two"><div class="field"><label>Nationality code</label><input id="nationality" value="${p.nationality||''}"></div><div class="field"><label>Place of birth code</label><input id="placeOfBirth" value="${p.placeOfBirth||''}"></div></div><div class="row two"><div class="field"><label>Sex</label><select id="sex"><option value="M">Male</option><option value="F">Female</option></select></div><div class="field"><label>Phone country code</label><input id="phoneCountry" value="${p.phoneCountry||''}"></div></div><div class="row two"><div class="field"><label>Email</label><input id="email" value="${p.email||''}"></div><div class="field"><label>Mobile no.</label><input id="mobile" value="${p.mobile||''}"></div></div>`}
function tabs(){return `<nav class="tabs"><button class="tab ${view==='home'?'active':''}" data-view="home">Home</button><button class="tab ${view==='profiles'?'active':''}" data-view="profiles">Profiles</button><button class="tab ${view==='settings'?'active':''}" data-view="settings">Settings</button><button class="tab ${view==='help'?'active':''}" data-view="help">Help</button></nav>`}
function wire(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-trip]').forEach(b=>b.onclick=()=>{selectedTrip=b.dataset.trip;view='trip';render()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{state.trip.transportNo=$('transportNo')?.value||state.trip.transportNo;save();copyPayload(b.dataset.copy)});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>location.href=officialUrl);document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{state.activeProfileId=b.dataset.profile;save();render()});document.querySelector('[data-add-profile]')?.addEventListener('click',()=>{const id='p'+Date.now();state.profiles.push({...defaults.profiles[0],id,label:'Traveller '+(state.profiles.length+1)});state.activeProfileId=id;save();render()});document.querySelector('[data-save-profile]')?.addEventListener('click',()=>{const p=activeProfile();['label','name','passportNo','dob','nationality','placeOfBirth','sex','passportExpiry','email','phoneCountry','mobile'].forEach(k=>p[k]=$(k).value.trim());save();alert('Profile saved');render()});document.querySelector('[data-save-settings]')?.addEventListener('click',()=>{['transportNo','lastPort','accommodationStay','address1','address2','state','city','postcode'].forEach(k=>state.trip[k]=$('d_'+k).value.trim().toUpperCase());state.trip.departureOffset=Number($('d_departureOffset').value);save();alert('Defaults saved');render()});if($('d_departureOffset')) $('d_departureOffset').value=String(state.trip.departureOffset||1);if($('sex')) $('sex').value=activeProfile().sex||'M';document.querySelector('[data-export]')?.addEventListener('click',()=>navigator.clipboard.writeText(JSON.stringify(state,null,2)).then(()=>alert('Backup copied')));document.querySelector('[data-import]')?.addEventListener('click',()=>{const s=prompt('Paste backup JSON');if(!s)return;try{state=JSON.parse(s);save();render()}catch(e){alert('Invalid JSON')}});document.querySelector('[data-reset]')?.addEventListener('click',()=>{if(confirm('Delete all local MDAC Express data?')){localStorage.removeItem(KEY);state=load();render()}})}
render();
