const KEY="mdacExpressV5";
const LEGACY_KEY="mdacExpressV4";
const officialUrl="https://imigresen-online.imi.gov.my/mdac/main?registerMain";
const appUrl="https://andrewpatterson-cloud.github.io/mdac-express/";
const version="1.1.0";

const defaults={
  profiles:[{id:"p1",label:"Traveller 1",name:"",passportNo:"",dob:"01/01/1970",nationality:"USA",placeOfBirth:"USA",sex:"M",passportExpiry:"01/01/2030",email:"",phoneCountry:"SGP",mobile:""}],
  activeProfileId:"p1",
  settings:{defaultTrip:"weekend",rememberHistory:true,creatorLinkedIn:"",showWelcome:true,statsEndpoint:""},
  history:{transport:[],hotel:[]},
  stats:{total:null,countries:[],lastChecked:null},
  trip:{transportNo:"",modeOfTravel:"LAND",lastPort:"SGP",accommodationStay:"OTHERS",address1:"106 JALAN WONG AH FOOK",address2:"JOHOR BAHRU CITY SQUARE",state:"JOHOR",city:"JOHOR BAHRU",postcode:"80000",departureOffset:1}
};
let state=load();let view=state.settings.showWelcome?"welcome":"home";let selectedTrip="weekend";

function merge(base, saved){
  const out={...base,...saved};
  out.settings={...base.settings,...(saved?.settings||{})};
  out.history={...base.history,...(saved?.history||{})};
  out.stats={...base.stats,...(saved?.stats||{})};
  out.trip={...base.trip,...(saved?.trip||{})};
  out.profiles=saved?.profiles?.length?saved.profiles:base.profiles;
  out.activeProfileId=saved?.activeProfileId||out.profiles[0].id;
  return out;
}
function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY)||"{}";return merge(defaults,JSON.parse(raw));}catch(e){return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function $(id){return document.getElementById(id)}
function activeProfile(){return state.profiles.find(p=>p.id===state.activeProfileId)||state.profiles[0]}
function fmtDate(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return String(d.getDate()).padStart(2,"0")+"/"+String(d.getMonth()+1).padStart(2,"0")+"/"+d.getFullYear()}
function payloadFor(kind=selectedTrip){
  const p=activeProfile();const isDay=kind==="day";const isFlight=kind==="flight";const isFerry=kind==="ferry";let mode=isFlight?"AIR":isFerry?"SEA":"LAND";
  return {profile:p,trip:{arrivalDate:fmtDate(0),departureDate:fmtDate(isDay?0:state.trip.departureOffset||1),modeOfTravel:mode,lastPort:state.trip.lastPort||"SGP",transportNo:state.trip.transportNo||"",accommodationStay:state.trip.accommodationStay||"OTHERS",address1:state.trip.address1,address2:state.trip.address2,state:state.trip.state,city:state.trip.city,postcode:state.trip.postcode}};
}
function copyPayload(kind){
  const data=payloadFor(kind);
  if(state.settings.rememberHistory && data.trip.transportNo){addHistory('transport',data.trip.transportNo)}
  save();
  navigator.clipboard.writeText("MDAC_EXPRESS:"+JSON.stringify(data)).then(()=>alert("MDAC prepared. Now tap Open Official MDAC. When the official page loads in Safari, tap Share, then tap Fill MDAC."));
}
function addHistory(type,val){val=(val||'').trim().toUpperCase();if(!val)return;state.history[type]=[val,...(state.history[type]||[]).filter(x=>x!==val)].slice(0,10)}

function render(){document.querySelector("#app").innerHTML=`<main class="shell">${header()}${views[view]()}${tabs()}</main>`;wire();maybeLoadStats();}
function header(){const p=activeProfile();return `<div class="top"><div class="brand"><div class="logo">🇲🇾</div><div><h1>MDAC Express</h1><p class="sub">${escapeHtml(p.label||"Traveller")} · local only · v${version}</p></div></div><button class="pill" data-view="profiles">Switch</button></div>`}
const tripTiles=[['weekend','🚗','Weekend Johor','Depart tomorrow'],['day','⚡','Day Trip','Return today'],['flight','✈️','Flight','Air arrival'],['bus','🚌','Bus','Land arrival'],['train','🚆','Train','Rail arrival'],['ferry','⛴️','Ferry','Sea arrival']];
const views={
welcome(){return `<section class="hero"><h2>Welcome to MDAC Express</h2><p>MDAC Express is for people who regularly complete the Malaysia Digital Arrival Card and are tired of repeatedly entering the same passport, contact and trip information.</p></section><div class="card"><h2>Purpose</h2><p class="bodycopy">Create a traveller profile once, save your usual trip defaults, then prepare the information needed for the official MDAC form in a few taps. MDAC Express does not replace the official website and does not submit anything for you. It helps you complete the official form faster while keeping you in control.</p><div class="notice">🔒 Your personal information is stored only on this device. No account. No server upload. No shared personal data.</div><button class="primary" data-accept-welcome>Get started</button><button class="secondary" data-view="help">Read full instructions</button></div>`},
home(){return `<section class="hero"><h2>Start your MDAC faster</h2><p>Choose a preset, enter only what changed, prepare your MDAC data, then use the Safari Shortcut on the official MDAC page.</p></section>${desktopQr()}<section class="grid">${tripTiles.map(t=>`<button class="tile" data-trip="${t[0]}"><span class="ico">${t[1]}</span><span class="title">${t[2]}</span><span class="hint">${t[3]}</span></button>`).join('')}</section><div class="card"><h2>Quick action</h2><button class="primary" data-copy="weekend">Prepare Weekend Johor</button><button class="secondary" data-open>Open official MDAC</button><button class="secondary" data-share>Share MDAC Express</button></div>${statsCard()}`},
trip(){const t=payloadFor(selectedTrip).trip;return `<button class="back" data-view="home">‹ Back</button><div class="card"><h2>${tripTiles.find(x=>x[0]===selectedTrip)?.[2]||'Trip'}</h2><div class="row"><div class="field"><label>Transport no.</label><input id="transportNo" value="${escapeHtml(state.trip.transportNo||'')}" placeholder="Car plate / flight / bus" /></div>${historyChips('transport')}</div><div class="row two"><div class="field"><label>Arrival</label><input disabled value="${t.arrivalDate}" /></div><div class="field"><label>Departure</label><input disabled value="${t.departureDate}" /></div></div><div class="notice">Mode: <b>${t.modeOfTravel}</b> · Last port: <b>${t.lastPort}</b> · Address: <b>${t.city}, ${t.state}</b></div><button class="primary" data-copy="${selectedTrip}">Prepare MDAC</button><button class="secondary" data-open>Open official MDAC</button></div>`},
profiles(){const p=activeProfile();return `<div class="card"><h2>Traveller profiles</h2><div class="list">${state.profiles.map(x=>`<button class="item" data-profile="${x.id}"><div><b>${escapeHtml(x.label)}</b><span>${x.passportNo?escapeHtml(x.passportNo):'No passport saved'}</span></div><span>${x.id===state.activeProfileId?'✓':''}</span></button>`).join('')}</div><button class="secondary" data-add-profile>Add profile</button><button class="secondary" data-duplicate-profile>Duplicate active profile</button></div><div class="card"><h2>Edit active profile</h2>${profileFields(p)}<button class="primary" data-save-profile>Save profile</button><button class="danger" data-delete-profile>Delete profile</button></div>`},
settings(){return `<div class="card"><h2>Trip defaults</h2><div class="row"><div class="field"><label>Default transport no.</label><input id="d_transportNo" value="${escapeHtml(state.trip.transportNo||'')}" /></div><div class="field"><label>Last port before Malaysia</label><input id="d_lastPort" value="${escapeHtml(state.trip.lastPort||'SGP')}" /></div><div class="field"><label>Accommodation type</label><input id="d_accommodationStay" value="${escapeHtml(state.trip.accommodationStay||'OTHERS')}" /></div><div class="field"><label>Address line 1</label><input id="d_address1" value="${escapeHtml(state.trip.address1||'')}" /></div><div class="field"><label>Address line 2</label><input id="d_address2" value="${escapeHtml(state.trip.address2||'')}" /></div></div><div class="row two"><div class="field"><label>State</label><input id="d_state" value="${escapeHtml(state.trip.state||'JOHOR')}" /></div><div class="field"><label>City</label><input id="d_city" value="${escapeHtml(state.trip.city||'JOHOR BAHRU')}" /></div></div><div class="row two"><div class="field"><label>Postcode</label><input id="d_postcode" value="${escapeHtml(state.trip.postcode||'80000')}" /></div><div class="field"><label>Departure offset</label><select id="d_departureOffset"><option value="0">Same day</option><option value="1">Tomorrow</option><option value="2">+2 days</option></select></div></div><button class="primary" data-save-settings>Save defaults</button></div><div class="card"><h2>Sharing and credit</h2><div class="field"><label>Andrew Patterson LinkedIn URL</label><input id="creatorLinkedIn" value="${escapeHtml(state.settings.creatorLinkedIn||'')}" placeholder="Paste your LinkedIn profile URL" /></div><button class="primary" data-save-credit>Save credit link</button><button class="secondary" data-share>Share MDAC Express</button></div><div class="card"><h2>Usage counter</h2><p class="bodycopy">GitHub Pages is static, so a real global usage counter needs a small analytics or serverless endpoint. Add an endpoint here later and the app will show total usage plus country flags.</p><div class="field"><label>Optional stats endpoint URL</label><input id="statsEndpoint" value="${escapeHtml(state.settings.statsEndpoint||'')}" placeholder="https://.../mdac-stats" /></div><button class="primary" data-save-stats>Save stats endpoint</button></div><div class="card"><h2>Data</h2><button class="secondary" data-export>Export backup</button><button class="secondary" data-import>Import backup</button><button class="danger" data-reset>Reset all data</button></div>`},
help(){return `<div class="card"><h2>Why this app exists</h2><p class="bodycopy">MDAC Express reduces repetitive data entry for the official Malaysia Digital Arrival Card. It is useful for frequent travellers because the official form asks for many details that rarely change, such as passport information, contact details and common travel defaults.</p><div class="notice">MDAC Express does not submit your arrival card. The official Malaysian Immigration website remains the only place where your information is submitted.</div></div><div class="card"><h2>Complete instructions</h2><ol class="steps"><li><b>Create your traveller profile.</b><br>Go to Profiles and enter your name, passport number, date of birth, passport expiry, nationality, email and mobile number.</li><li><b>Save your usual trip defaults.</b><br>Go to Settings and choose defaults such as Land, Air or Sea, last port before Malaysia, Johor address, city, state and postcode.</li><li><b>Prepare each trip.</b><br>Choose Weekend Johor, Day Trip, Flight, Bus, Train, Ferry or Custom. Enter anything that changed, such as vehicle registration, flight number or hotel.</li><li><b>Tap Prepare MDAC.</b><br>The app creates a secure autofill payload and copies it to your clipboard. Personal data is not shared when you share the app link.</li><li><b>Open the official MDAC website.</b><br>Tap Open Official MDAC. Wait for the official form to load in Safari.</li><li><b>Run the Safari Shortcut.</b><br>On the official MDAC page, tap the Safari Share button, the square with the upward arrow. Scroll down the share sheet and tap <b>Fill MDAC</b>. The Shortcut reads the prepared payload from your clipboard and fills the form.</li><li><b>Review before submitting.</b><br>Check every field, complete the CAPTCHA yourself, then press Submit on the official MDAC website.</li></ol></div><div class="card"><h2>Why the Safari Shortcut is needed</h2><p class="bodycopy">Browsers prevent one website from changing another website for security reasons. The Shortcut runs only after you open the official MDAC page yourself and choose Fill MDAC from Safari's Share menu.</p><button class="secondary" data-open>Open official MDAC</button></div>`},
about(){return `<div class="card"><h2>About MDAC Express</h2><p class="bodycopy">Built by <b>Andrew Patterson</b> to make repeat travel into Malaysia faster and less repetitive.</p><div class="notice">This is an independent helper. It is not affiliated with Malaysian Immigration. Always review your official MDAC before submitting.</div>${state.settings.creatorLinkedIn?`<a class="linkbtn" href="${escapeAttr(state.settings.creatorLinkedIn)}" target="_blank" rel="noopener">Andrew Patterson on LinkedIn</a>`:`<p class="sub">Add Andrew's LinkedIn URL in Settings to show a public credit link.</p>`}<button class="secondary" data-share>Share MDAC Express</button></div>${statsCard()}${desktopQr()}`}
};
function desktopQr(){return `<div class="card desktop-only"><h2>Open on your phone</h2><p class="bodycopy">Scan this QR code to load MDAC Express on mobile.</p><img class="qr" alt="QR code for MDAC Express" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(appUrl)}"><p class="sub">${appUrl}</p></div>`}
function statsCard(){const countries=state.stats.countries?.length?state.stats.countries:[{flag:'🇸🇬',name:'Singapore',count:null},{flag:'🇲🇾',name:'Malaysia',count:null},{flag:'🌍',name:'Other countries',count:null}];return `<div class="card"><h2>Community stats</h2><div class="statbig">${state.stats.total??'—'}<span> travellers helped</span></div><div class="flaggrid">${countries.map(c=>`<div class="flag"><b>${c.flag}</b><span>${escapeHtml(c.name)}</span><em>${c.count??'—'}</em></div>`).join('')}</div><p class="sub">Global stats require an optional privacy-friendly counter endpoint. Until then, no tracking is active.</p></div>`}
function historyChips(type){const items=state.history[type]||[];if(!items.length)return '';return `<div class="chips">${items.map(x=>`<button class="chip" data-history="${escapeAttr(x)}">${escapeHtml(x)}</button>`).join('')}</div>`}
function profileFields(p){return `<div class="row"><div class="field"><label>Profile label</label><input id="label" value="${escapeHtml(p.label||'')}"></div><div class="field"><label>Full name as in passport</label><input id="name" value="${escapeHtml(p.name||'')}"></div><div class="field"><label>Passport no.</label><input id="passportNo" value="${escapeHtml(p.passportNo||'')}"></div></div><div class="row two"><div class="field"><label>DOB DD/MM/YYYY</label><input id="dob" value="${escapeHtml(p.dob||'')}"></div><div class="field"><label>Passport expiry</label><input id="passportExpiry" value="${escapeHtml(p.passportExpiry||'')}"></div></div><div class="row two"><div class="field"><label>Nationality code</label><input id="nationality" value="${escapeHtml(p.nationality||'')}"></div><div class="field"><label>Place of birth code</label><input id="placeOfBirth" value="${escapeHtml(p.placeOfBirth||'')}"></div></div><div class="row two"><div class="field"><label>Sex</label><select id="sex"><option value="M">Male</option><option value="F">Female</option></select></div><div class="field"><label>Phone country code</label><input id="phoneCountry" value="${escapeHtml(p.phoneCountry||'')}"></div></div><div class="row two"><div class="field"><label>Email</label><input id="email" value="${escapeHtml(p.email||'')}"></div><div class="field"><label>Mobile no.</label><input id="mobile" value="${escapeHtml(p.mobile||'')}"></div></div>`}
function tabs(){return `<nav class="tabs"><button class="tab ${view==='home'?'active':''}" data-view="home">Home</button><button class="tab ${view==='profiles'?'active':''}" data-view="profiles">Profiles</button><button class="tab ${view==='settings'?'active':''}" data-view="settings">Settings</button><button class="tab ${view==='help'?'active':''}" data-view="help">Help</button><button class="tab ${view==='about'?'active':''}" data-view="about">About</button></nav>`}
function wire(){
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
  document.querySelectorAll('[data-trip]').forEach(b=>b.onclick=()=>{selectedTrip=b.dataset.trip;view='trip';render()});
  document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{state.trip.transportNo=$('transportNo')?.value||state.trip.transportNo;save();copyPayload(b.dataset.copy)});
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>location.href=officialUrl);
  document.querySelectorAll('[data-share]').forEach(b=>b.onclick=shareApp);
  document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{state.activeProfileId=b.dataset.profile;save();render()});
  document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{if($('transportNo')) $('transportNo').value=b.dataset.history});
  document.querySelector('[data-accept-welcome]')?.addEventListener('click',()=>{state.settings.showWelcome=false;save();view='home';render()});
  document.querySelector('[data-add-profile]')?.addEventListener('click',()=>{const id='p'+Date.now();state.profiles.push({...defaults.profiles[0],id,label:'Traveller '+(state.profiles.length+1)});state.activeProfileId=id;save();render()});
  document.querySelector('[data-duplicate-profile]')?.addEventListener('click',()=>{const id='p'+Date.now();const p={...activeProfile(),id,label:(activeProfile().label||'Traveller')+' copy'};state.profiles.push(p);state.activeProfileId=id;save();render()});
  document.querySelector('[data-delete-profile]')?.addEventListener('click',()=>{if(state.profiles.length<2)return alert('Keep at least one profile.');if(confirm('Delete this profile?')){state.profiles=state.profiles.filter(p=>p.id!==state.activeProfileId);state.activeProfileId=state.profiles[0].id;save();render()}});
  document.querySelector('[data-save-profile]')?.addEventListener('click',()=>{const p=activeProfile();['label','name','passportNo','dob','nationality','placeOfBirth','sex','passportExpiry','email','phoneCountry','mobile'].forEach(k=>p[k]=$(k).value.trim());save();alert('Profile saved');render()});
  document.querySelector('[data-save-settings]')?.addEventListener('click',()=>{['transportNo','lastPort','accommodationStay','address1','address2','state','city','postcode'].forEach(k=>state.trip[k]=$('d_'+k).value.trim().toUpperCase());state.trip.departureOffset=Number($('d_departureOffset').value);save();alert('Defaults saved');render()});
  document.querySelector('[data-save-credit]')?.addEventListener('click',()=>{state.settings.creatorLinkedIn=$('creatorLinkedIn').value.trim();save();alert('Credit link saved')});
  document.querySelector('[data-save-stats]')?.addEventListener('click',()=>{state.settings.statsEndpoint=$('statsEndpoint').value.trim();save();alert('Stats endpoint saved')});
  if($('d_departureOffset')) $('d_departureOffset').value=String(state.trip.departureOffset||1);if($('sex')) $('sex').value=activeProfile().sex||'M';
  document.querySelector('[data-export]')?.addEventListener('click',()=>navigator.clipboard.writeText(JSON.stringify(state,null,2)).then(()=>alert('Backup copied')));
  document.querySelector('[data-import]')?.addEventListener('click',()=>{const s=prompt('Paste backup JSON');if(!s)return;try{state=merge(defaults,JSON.parse(s));save();render()}catch(e){alert('Invalid JSON')}});
  document.querySelector('[data-reset]')?.addEventListener('click',()=>{if(confirm('Delete all local MDAC Express data?')){localStorage.removeItem(KEY);state=load();view='welcome';render()}})
}
async function shareApp(){const data={title:'MDAC Express',text:'MDAC Express helps frequent Malaysia travellers prepare the official MDAC form faster. Personal data stays on your own device.',url:appUrl}; if(navigator.share){try{await navigator.share(data)}catch(e){}}else{await navigator.clipboard.writeText(`${data.text} ${data.url}`);alert('Share link copied. Personal profile data was not included.')}}
async function maybeLoadStats(){const endpoint=state.settings.statsEndpoint;if(!endpoint)return;if(Date.now()-(state.stats.lastChecked||0)<3600000)return;try{const r=await fetch(endpoint,{method:'GET',cache:'no-store'});const data=await r.json();state.stats={total:data.total??null,countries:Array.isArray(data.countries)?data.countries:[],lastChecked:Date.now()};save();}catch(e){}}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function escapeAttr(s){return escapeHtml(s).replace(/'/g,'&#39;')}
render();
